version: '3.7'
services:
  node-app:
    build: .
    image: postgres:lateset
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=wndryn
      - POSTGRES_PASSWORD=noneofyourbusiness